### ISSUE TITLE
프로젝트 컨벤션 정하기

### ISSUE THREAD

**Issue by aorri2** [f-lab-edu/Goods-For-You#1]
## ☑️ TODO List

- [x] Issue 컨벤션 정하기
- [x] Pull Request Rule 정하기
- [x] Commit 컨벤션 정하기
- [x] Branch 전략 정하기
   - GitFlow 전략을 사용

**Comment by f-lab-bradley** [comment]
하나하나 TODO 를 만들어 작성하는 방식으로 생각하셨나요? 
그렇다면 PR 을 만들어 주시고 Draft 로 변경 해 주세요.
그리고 한가지  Task 가 끝날 때 마다 commit 을 해 주세요.
그 뒤 작업이 전부 끝나면 ready to review 로 전환 해 주시면 됩니다.

그럼 팀원이 현재 진행 상황을 파악 하기가 훨씬 쉬워요

**Comment by aorri2** [comment]
- Draft 모드인 PR 이슈는 머지 버튼이 활성화 되지 않는다.
- Ready for review 버튼을 누르면 Draft 모드에서 일반 PR 이슈로 전환되어 코드를 머지할 수 있게 된다.

현재 작업이 완료되지 않은 README.md 수정 PR Draft 모드로 변경 해놓도록 하겠습니다 감사합니다😊
