### ISSUE TITLE
프로젝트 구성도 작성

### ISSUE THREAD

**Issue by aorri2** [f-lab-edu/Goods-For-You#4]
## ✔ TODO

- [x] Scale in / Scale Out 과 High availability(고 가용성)을 중점적으로 고려해서 구성도 초기 버전 작성.
- [x] **Elastic Load Balancer(ELB)**와 **Nginx**그리고 두개와 **관련된 키워드**에 대해 학습.
- [x] 프로젝트 구성도 작성 시, **ELB** 와 **Nginx** 중 한 개만 사용할 것인지, **둘다 사용**할 것인지 또는 **다른 솔루션**을 사용할 것인지에 대해서도 고민.
- [x] 회원 인증 설계 관련 내용 프로젝트에 구현 후 구성도에 추가

**Comment by aorri2** [comment]
[블로그](https://simgee.tistory.com/32) 체크박스 2,3번에 관련된 내용에 대해 학습 후 정리해 보았습니다

**Comment by aorri2** [comment]
구성도 초기 버전은 프로젝트 Wiki에 작성 완료 하였습니다.
